// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/zhi/temp/code/go/example/cgo/00_cgo.go:1:1
package main

////import "C" 更像是一个关键词, CGO 工具在预处理会删除这一行
//#include <stdio.h> // 序文件中可以链接标准 C 程序库
import _ "unsafe"

// build :
// -x 选项可以查看 go 程序编译过程中执行所有指令
// go build -x 00_cgo.go
func main() {
	( /*line :11:2*/_Cfunc_puts /*line :11:7*/)(( /*line :11:9*/_Cfunc_CString /*line :11:17*/)("Hello, CGO"))
}

// go tool cgo
