// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype__GoString_ string

type _Ctype_char int8

type _Ctype_int int32

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

//go:notinheap
type _Ctype_void_notinheap struct{}

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})


func _Cfunc_CString(s string) *_Ctype_char {
	p := _cgo_cmalloc(uint64(len(s)+1))
	pp := (*[1<<30]byte)(p)
	copy(pp[:], s)
	pp[len(s)] = 0
	return (*_Ctype_char)(p)
}
//go:cgo_import_static _cgo_7fc5a4e65122_Cfunc_puts
//go:linkname __cgofn__cgo_7fc5a4e65122_Cfunc_puts _cgo_7fc5a4e65122_Cfunc_puts
var __cgofn__cgo_7fc5a4e65122_Cfunc_puts byte
var _cgo_7fc5a4e65122_Cfunc_puts = unsafe.Pointer(&__cgofn__cgo_7fc5a4e65122_Cfunc_puts)

//go:cgo_unsafe_args
func _Cfunc_puts(p0 *_Ctype_char) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_7fc5a4e65122_Cfunc_puts, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}

//go:cgo_import_static _cgo_7fc5a4e65122_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_7fc5a4e65122_Cfunc__Cmalloc _cgo_7fc5a4e65122_Cfunc__Cmalloc
var __cgofn__cgo_7fc5a4e65122_Cfunc__Cmalloc byte
var _cgo_7fc5a4e65122_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_7fc5a4e65122_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_7fc5a4e65122_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
